# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62c7124cccb56a6745b25a5745048e43e76ce14c592ae954a4ab3eb1bf0caf3783e232e706e0083176c482ee1f3d78520b3e4cdf275dc20a8f18aac434d6b27c

test:
  secret_key_base: 26beaed6342c9aac2f4f050cff41ae0df88ea0140a0f57f966ba7dd164f7e6f7628f89af5a88026d6470e970eab9a681f2b7e1243afa27e15f94fdb4a1b277a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
